"use client";

import { useId, useState } from "react";

import { LearnerApiError, askTutor } from "@/lib/learner-api";
import { TUTOR_TASK, type TutorResponse, type TutorTask } from "@/types/academy";

type Outcome =
  | { state: "idle" }
  | { state: "loading" }
  | { state: "answered"; response: TutorResponse }
  | { state: "failed"; message: string };

/** The tasks offered to the learner, in the order they are most likely to be wanted. */
const ACTIONS: { task: TutorTask; label: string; needsText: "no" | "draft" }[] = [
  { task: TUTOR_TASK.hint, label: "Give me a nudge", needsText: "no" },
  { task: TUTOR_TASK.explanation, label: "Explain this step", needsText: "no" },
  { task: TUTOR_TASK.socraticQuestion, label: "Ask me a question", needsText: "no" },
  { task: TUTOR_TASK.misconceptionCheck, label: "What do people get wrong?", needsText: "no" },
  { task: TUTOR_TASK.feedback, label: "Check my draft", needsText: "draft" },
];

/**
 * The "Ask for help" surface.
 *
 * It calls the API and renders what comes back. It deliberately holds no history: the
 * previous answer is replaced, and neither the question nor the draft is stored anywhere.
 */
export function TutorPanel({
  conceptId,
  learnerId,
  stepIndex,
}: {
  conceptId: string;
  learnerId: string | null;
  stepIndex: number | null;
}) {
  const [text, setText] = useState("");
  const [outcome, setOutcome] = useState<Outcome>({ state: "idle" });
  const textareaId = useId();

  const ask = async (task: TutorTask) => {
    setOutcome({ state: "loading" });
    try {
      const response = await askTutor({
        task,
        conceptId,
        ...(stepIndex === null ? {} : { stepIndex }),
        ...(learnerId === null ? {} : { learnerId }),
        ...(text.trim() ? { question: text.trim() } : {}),
      });
      setOutcome({ state: "answered", response });
    } catch (error) {
      setOutcome({
        state: "failed",
        message:
          error instanceof LearnerApiError && error.status === 0
            ? "We cannot reach the Academy right now, so help is unavailable. The lesson text above still works."
            : error instanceof Error
              ? error.message
              : "Help is unavailable right now.",
      });
    }
  };

  return (
    <section
      data-testid="tutor-panel"
      aria-labelledby="tutor-heading"
      className="space-y-4 rounded-lg border border-white/10 p-5"
    >
      <h2 id="tutor-heading" className="text-sm font-semibold uppercase tracking-widest">
        Ask for help
      </h2>

      <p className="text-xs text-(--color-ink-muted)">
        This help is generated by reading the published lesson, not by an AI model. It can quote
        and rearrange what the lesson already says, and nothing else. Your question and draft are
        not saved.
      </p>

      <div className="space-y-2">
        <label htmlFor={textareaId} className="block text-sm text-(--color-ink-muted)">
          Optional: type a question, or paste the explanation you are drafting.
        </label>
        <textarea
          id={textareaId}
          value={text}
          onChange={(event) => setText(event.target.value)}
          rows={3}
          maxLength={1000}
          className="w-full rounded-md border border-white/15 bg-black/30 p-3 text-sm focus-visible:outline-2 focus-visible:outline-(--color-accent)"
        />
      </div>

      <div className="flex flex-wrap gap-2">
        {ACTIONS.map((action) => (
          <button
            key={action.task}
            type="button"
            data-testid={`tutor-${action.task}`}
            disabled={
              outcome.state === "loading" || (action.needsText === "draft" && !text.trim())
            }
            onClick={() => void ask(action.task)}
            className="rounded-md border border-white/20 px-3 py-1.5 text-sm focus-visible:outline-2 focus-visible:outline-(--color-accent) disabled:opacity-40"
          >
            {action.label}
          </button>
        ))}
      </div>

      <div aria-live="polite" aria-busy={outcome.state === "loading"}>
        {outcome.state === "idle" ? (
          <p className="text-sm text-(--color-ink-muted)">
            Nothing asked yet. Pick one of the options above whenever you are stuck.
          </p>
        ) : null}

        {outcome.state === "loading" ? (
          <p role="status" className="text-sm text-(--color-ink-muted)">
            Reading the lesson…
          </p>
        ) : null}

        {outcome.state === "failed" ? (
          <p
            role="alert"
            data-testid="tutor-failure"
            className="rounded-lg border border-amber-400/40 bg-amber-400/10 p-4 text-sm"
          >
            {outcome.message}
          </p>
        ) : null}

        {outcome.state === "answered" ? <Answer response={outcome.response} /> : null}
      </div>
    </section>
  );
}

function Answer({ response }: { response: TutorResponse }) {
  return (
    <article
      data-testid="tutor-answer"
      data-supported={response.supported ? "true" : "false"}
      className={`space-y-3 rounded-lg border p-4 ${
        response.supported ? "border-white/10 bg-white/5" : "border-amber-400/40 bg-amber-400/10"
      }`}
    >
      <h3 className="text-sm font-semibold">{response.headline}</h3>

      {response.supported ? null : (
        <p data-testid="tutor-unsupported" className="text-xs uppercase tracking-widest">
          Outside this lesson
        </p>
      )}

      <ul className="space-y-2 text-sm">
        {response.body.map((passage, index) => (
          <li key={index}>{passage}</li>
        ))}
      </ul>

      {response.followUp ? (
        <p className="text-sm text-(--color-ink-muted)">{response.followUp}</p>
      ) : null}

      <footer className="space-y-1 border-t border-white/10 pt-3 text-xs text-(--color-ink-muted)">
        <p data-testid="tutor-disclaimer">{response.disclaimer}</p>
        <p>
          Source: {response.provider.name} ({response.provider.determinism},{" "}
          {response.provider.external ? "external service" : "runs locally, no external service"}).
        </p>
        {response.citations.length > 0 ? (
          <p>
            Drawn from: {response.citations.map((citation) => citation.field).join(", ")} in{" "}
            {response.conceptId} {response.citations[0]?.conceptVersion}.
          </p>
        ) : null}
      </footer>
    </article>
  );
}
